name: victim-merge-queue-workflow

on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: victim code
      run:  echo "helo"
    - name: Run slow CI (emulated by a long sleep)
      run: sleep 300
